apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80         # Internal HTTP port
      targetPort: 4499 # Port on the container
    - protocol: TCP
      port: 443        # Internal HTTPS port
      targetPort: 4499 # Port on the container
  type: NodePort
